trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Scan
  jobs:
  - job: BridgecrewScan
    steps:
    - checkout: self

    - script: npm config set registry https://registry.npmjs.org/
      displayName: 'Set npm Registry'

    - script: npm install -g bridgecrew
      displayName: 'Install Bridgecrew CLI'

    - script: bridgecrew -t $(BRIDGECREW_API_KEY) -d $(System.DefaultWorkingDirectory)
      displayName: 'Run Bridgecrew Scan'
      env:
        BRIDGECREW_API_KEY: $(BRIDGECREW_API_KEY)
